import 'package:meta/meta.dart';

class User {

  final String uid; //unique user identifier key. generated by firebase auth
  final String name; //the display name other users are seeing
  final String email; //the email bookery can send emails to. optionally public in profile

  User({
    @required this.uid,
    //optional
    this.name,
    this.email
  });

  //convert firestore document format to user model
  User.fromData(Map<String, dynamic> data) :
    uid = data["uid"],
    name = data["name"],
    email = data["email"];

  //convert user model to firestore document format
  Map<String, dynamic> toJson() {
    return {
      "uid": uid,
      "name": name,
      "email": email
    };
  }

}